name: PullRequest_INOEKaKEE
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  script-summary:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      id: send_info_pull_requests
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const title = github.event.pull_request.title;
          const newTitle = "井上"; // 新しいタイトルを設定

          const octokit = new Octokit({
            auth: process.env.GITHUB_TOKEN,
          });

          // タイトルを更新
          octokit.pulls.update({
            owner: github.context.repo.owner,
            repo: github.context.repo.repo,
            pull_number: github.context.payload.pull_request.number,
            title: newTitle,
          });