name: PullRequest_Inoue
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  name: Update Pull Request Title
  run: |
    PR_NUMBER=${{ github.event.pull_request.number }}
    NEW_TITLE="新しいタイトル"

    # GitHub APIを使用してタイトルを変更
    curl -X PATCH -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
      -d "{\"title\":\"$NEW_TITLE\"}" \
      "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER"