name: Slack Notification Demo
on: push
env:
  SLACK_WEBHOOK: ${{ SLACK_WEBHOOK_URL }}

jobs:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          text: Hello,Slack