name: PullRequest_Confirm
on:
  pull_request:
    branches:
      - main
    types:
      - opened
  workflow_dispatch:
jobs:
  script-summary:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      id: send_info_pull_requests
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
            const pullRequest = context.payload.pull_request;
            if (pullRequest) {
              const pullTitle = pullRequest.title;
              const pullUrl = pullRequest.html_url;
               const pullNumber = pullRequest.number;
              const pullAuthor = pullRequest.user.login;

              // プルリクエストの詳細情報を取得
              const pullRequestResponse = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pullNumber
              });

              const assigneesResponse = await github.rest.issues.listAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pullNumber
              });

              const assignees = assigneesResponse.data.map(assignee => assignee.login);

              const requestedReviewersResponse = await github.rest.pulls.listRequestedReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pullNumber
              });

              const requestedReviewers = requestedReviewersResponse.data.users.map(reviewer => reviewer.login);

              let summary = `新しいプルリクエストが作成されました！\n\n`;
              summary += `タイトル: ${pullTitle}\n`;
              summary += `作成者: ${pullAuthor}\n`;
              summary += `URL: ${pullUrl}\n`;
              if (assignees.length > 0) {
                summary += `割り当てられたユーザー: ${assignees.join(', ')}\n`;
              }
              if (requestedReviewers.length > 0) {
                summary += `レビュアー: ${requestedReviewers.join(', ')}\n`;
              }

              core.setOutput('value', summary);

              await core.summary
                .addHeading('New Pull Request Created')
                .addText(summary)
                .write();
            }

    - uses: slackapi/slack-github-action@v1.16.0
      with:
        payload: "{\"text\":\"${{ steps.send_info_pull_requests.outputs.value }}\"}"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}