name: PullRequest_Info
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  send_info_pull_request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      id: send_info_pull_requests
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
              const url = github.event.pull_request.html_url;
              const title = github.event.pull_request.title;
              const assignees = github.event.pull_request.assignees;
              const assign = JSON.stringify(assignees)
              const requested_reviewers = github.event.pull_request.requested_reviewers;
              const reviewers = JSON.stringify(requested_reviewers)
              const mergeable = github.event.pull_request.mergeable;

              if(mergerable)
              {
                let summary = "";
                summary += url;
                summary += title + "\\n";
                summary += assign + "\\n";
                summary += reviewers + "\\n";
                
                core.setOutput('value', '<!here>\\n' + '以下のプルリクエストが作成されました\\n' + 
                'Title    : ' + title + '\\n' +
                'URL      : ' + url + '\\n' +
                'Author   : ' + assignees + '\\n' );

                await core.summary
                  .addHeading('New Pull Request Created')
                  .addRaw(summary)
                  .write();
              }
            }
    - uses: slackapi/slack-github-action@v1.16.0
      with:
        payload: "{\"text\":\"${{ steps.send_info_pull_requests.outputs.value }}\"}"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}