name: PullRequest_Confirm
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  test-message:
    timeout-minutes: 2
    runs-on: ubuntu-latests
    steps:
    - name: member1
      if: github.event.pull_request.requested_reviewers[0].login == 'yus-sasaki'
      run: echo "Login_Name=U01AQ8QSCH5" >> "$GITHUB_ENV"
    - name: member2
      if: github.event.pull_request.requested_reviewers[0].login == 'kojimadev'
      run: echo "Login_Name=U20M5MPMZ" >> "$GITHUB_ENV"
    - name: member3
      if: github.event.pull_request.requested_reviewers[0].login == 'takuma-kondo'
      run: echo "Login_Name=U04864XKT5J" >> "$GITHUB_ENV"
    - uses: slackapi/slack-github-action@v1.16.0
      with:
        payload: "{\"text\":\" <@${{ env.Login_Name }}>\\n 以下のプルリクエストを作成しました。\\n 
         Title     : ${{ github.event.pull_request.title}}\\n 
         URL       : ${{ github.event.pull_request.html_url}}\\n
         Assignees : ${{ github.event.pull_request.assignees[0].login}}\\n
         Revwer    : ${{ github.event.pull_request.requested_reviewers[0].login}}\"}"     
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
