name: PullRequest_Confirm
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  test-message:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: slackapi/slack-github-action@v1.16.0
      if: ${{ github.event.pull_request.requested_reviewers[0].login == 'yus-sasaki' }}
      with:
        payload: "{\"text\":\" <!U01AQ8QSCH5>\\n 佐々木さん。以下のプルリクエストを作成しました。\\n 
         Title   : ${{ github.event.pull_request.title}}\\n 
         URL     : ${{ github.event.pull_request.html_url}}\\n
         Revwer : ${{ github.event.pull_request.requested_reviewers[0].login　}}\"}"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
    - uses: slackapi/slack-github-action@v1.16.0
      if: ${{ github.event.pull_request.requested_reviewers[0].login == '' }}
      with:
        payload: "{\"text\":\" <!channel>\\n 近藤さん。以下のプルリクエストを作成しました。\\n 
         Title   : ${{ github.event.pull_request.title}}\\n 
         URL     : ${{ github.event.pull_request.html_url}}\\n
         Revwer : ${{ github.event.pull_request.requested_reviewers[0].login　}}\"}"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

