name: PullRequest_Confirm
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  test-message:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: slackapi/slack-github-action@v1.16.0
      with:
        payload: "{\"text\":\" 以下のプルリクエストが作成されました。:\\n 
         Title : ${{ github.event.pull_request.number}}\\n 
         URL   : ${{ github.event.pull_request.html_url}}\"}"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

