name: PullRequest_Confirm
on:
  pull_request:
    branches:
      - main
    types:
      - opened
  workflow_dispatch:
jobs:
  test-message:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      id: pr_info
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
            let pull_request_url = "${{ github.event.pull_request.html_url }}"
    - uses: slackapi/slack-github-action@v1.16.0
      with:
        payload: "{\"text\":\"Pull Request URL: ${{ steps.pr_info.outputs.pull_request_url }}\"}"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}