name: PullRequest_Confirm
on:
  pull_request:
    branches:
      - main
    types:
      - opened
  workflow_dispatch:
jobs:
  test-message:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: slackapi/slack-github-action@v1.16.0
      with:
        payload: "{\"text\":\"${URL}\"}"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}