name: Push_Message
on:
  push:
    branches:
      - 'main'
jobs:
  test-message:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:        
    - uses: slackapi/slack-github-action@v1.16.0 
      with:
        payload: {"text":"プッシュしました。"}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
