on:
  push:
    branches:
      - 'main'
  jobs:
  change_title:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
  
    - name: Change commit message title
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git log -1 --pretty=format:"%h" > commit_hash.txt
        COMMIT_HASH=$(cat commit_hash.txt)
        git commit --amend -m "New Commit Title" --no-edi
        git push -f origin HEA